/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertType = IDL.Variant({
  'AKI' : IDL.Null,
  'Hypotension' : IDL.Null,
  'CriticalLab' : IDL.Null,
  'Sepsis' : IDL.Null,
  'DrugInteraction' : IDL.Null,
  'Hypoxia' : IDL.Null,
  'AllergyContraindication' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'Info' : IDL.Null,
  'Critical' : IDL.Null,
  'Warning' : IDL.Null,
});
export const ClinicalAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : AlertType,
  'acknowledgedAt' : IDL.Opt(IDL.Int),
  'acknowledgedBy' : IDL.Opt(IDL.Principal),
  'patientId' : IDL.Nat,
  'isAcknowledged' : IDL.Bool,
  'isResolved' : IDL.Bool,
  'triggeredAt' : IDL.Int,
  'triggeredBy' : IDL.Text,
  'message' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
  'severity' : AlertSeverity,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const ObservationStatus = IDL.Variant({
  'Corrected' : IDL.Null,
  'Final' : IDL.Null,
  'Preliminary' : IDL.Null,
});
export const ObservationType = IDL.Variant({
  'Lab' : IDL.Null,
  'ExamFinding' : IDL.Null,
  'DrainMonitoring' : IDL.Null,
  'IntakeOutput' : IDL.Null,
  'Vital' : IDL.Null,
});
export const StaffRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'medical_officer' : IDL.Null,
  'intern_doctor' : IDL.Null,
  'consultant_doctor' : IDL.Null,
  'staff' : IDL.Null,
  'nurse' : IDL.Null,
});
export const VersionedRecord = IDL.Record({
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'version' : IDL.Nat,
  'createdByName' : IDL.Text,
  'createdByRole' : StaffRole,
  'changeReason' : IDL.Opt(IDL.Text),
});
export const Observation = IDL.Record({
  'id' : IDL.Nat,
  'status' : ObservationStatus,
  'isDeleted' : IDL.Bool,
  'numericValue' : IDL.Opt(IDL.Float64),
  'value' : IDL.Text,
  'observationDate' : IDL.Int,
  'patientId' : IDL.Nat,
  'observationType' : ObservationType,
  'code' : IDL.Text,
  'unit' : IDL.Text,
  'recordedBy' : IDL.Principal,
  'normalRange' : IDL.Opt(IDL.Text),
  'recordedByName' : IDL.Text,
  'recordedByRole' : StaffRole,
  'interpretation' : IDL.Opt(IDL.Text),
  'versionInfo' : VersionedRecord,
  'encounterId' : IDL.Opt(IDL.Nat),
});
export const BedStatus = IDL.Variant({
  'Empty' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Occupied' : IDL.Null,
});
export const BedTransferEntry = IDL.Record({
  'toBed' : IDL.Text,
  'date' : IDL.Int,
  'fromBed' : IDL.Text,
  'reason' : IDL.Text,
});
export const BedRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : BedStatus,
  'patientId' : IDL.Opt(IDL.Nat),
  'admissionDate' : IDL.Opt(IDL.Int),
  'transferHistory' : IDL.Vec(BedTransferEntry),
  'ward' : IDL.Text,
  'bedNumber' : IDL.Text,
  'patientName' : IDL.Opt(IDL.Text),
  'dischargeDate' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoteType = IDL.Variant({
  'SOAP' : IDL.Null,
  'Nursing' : IDL.Null,
  'DailyProgress' : IDL.Null,
  'General' : IDL.Null,
  'Handover' : IDL.Null,
  'Discharge' : IDL.Null,
});
export const ClinicalNote = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'patientId' : IDL.Nat,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'authorRole' : StaffRole,
  'noteType' : NoteType,
  'isDraft' : IDL.Bool,
  'previousVersionIds' : IDL.Vec(IDL.Nat),
  'versionInfo' : VersionedRecord,
  'encounterId' : IDL.Opt(IDL.Nat),
  'noteSubtype' : IDL.Opt(IDL.Text),
});
export const DiagnosisTemplate = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'icdCode' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'defaultDrugs' : IDL.Vec(IDL.Text),
  'defaultAdvice' : IDL.Vec(IDL.Text),
  'defaultInvestigations' : IDL.Vec(IDL.Text),
  'diagnosisNameBn' : IDL.Opt(IDL.Text),
  'diagnosisName' : IDL.Text,
  'defaultAdviceBn' : IDL.Vec(IDL.Text),
});
export const EncounterType = IDL.Variant({
  'IPD' : IDL.Null,
  'OPD' : IDL.Null,
  'FollowUp' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const EncounterStatus = IDL.Variant({
  'Planned' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Encounter = IDL.Record({
  'id' : IDL.Nat,
  'status' : EncounterStatus,
  'encounterType' : EncounterType,
  'endDate' : IDL.Opt(IDL.Int),
  'patientId' : IDL.Nat,
  'previousVersions' : IDL.Vec(VersionedRecord),
  'providerName' : IDL.Text,
  'providerId' : IDL.Principal,
  'versionInfo' : VersionedRecord,
  'encounterId' : IDL.Text,
  'locationNotes' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Int,
});
export const OrderType = IDL.Variant({
  'Medication' : IDL.Null,
  'Procedure' : IDL.Null,
  'Investigation' : IDL.Null,
  'LabTest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'Requested' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ClinicalOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'result' : IDL.Opt(IDL.Text),
  'patientId' : IDL.Nat,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'orderType' : OrderType,
  'orderedAt' : IDL.Int,
  'orderedBy' : IDL.Principal,
  'notes' : IDL.Opt(IDL.Text),
  'orderedByName' : IDL.Text,
  'orderedByRole' : StaffRole,
  'versionInfo' : VersionedRecord,
  'encounterId' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientType = IDL.Variant({
  'admitted' : IDL.Null,
  'outdoor' : IDL.Null,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'nameBn' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Opt(Time),
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'pastSurgicalHistory' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'patientType' : PatientType,
  'chronicConditions' : IDL.Vec(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'allergies' : IDL.Vec(IDL.Text),
});
export const Medication = IDL.Record({
  'duration' : IDL.Text,
  'dose' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'frequency' : IDL.Text,
});
export const Prescription = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'diagnosis' : IDL.Opt(IDL.Text),
  'prescriptionDate' : Time,
  'medications' : IDL.Vec(Medication),
  'notes' : IDL.Opt(IDL.Text),
  'visitId' : IDL.Opt(IDL.Nat),
});
export const VitalSigns = IDL.Record({
  'respiratoryRate' : IDL.Opt(IDL.Text),
  'temperature' : IDL.Opt(IDL.Text),
  'bloodPressure' : IDL.Opt(IDL.Text),
  'oxygenSaturation' : IDL.Opt(IDL.Text),
  'pulse' : IDL.Opt(IDL.Text),
});
export const VisitType = IDL.Variant({
  'admitted' : IDL.Null,
  'outdoor' : IDL.Null,
});
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'vitalSigns' : VitalSigns,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'visitDate' : Time,
  'visitType' : VisitType,
  'diagnosis' : IDL.Opt(IDL.Text),
  'historyOfPresentIllness' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'physicalExamination' : IDL.Opt(IDL.Text),
  'chiefComplaint' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'changedByName' : IDL.Text,
  'changedByRole' : StaffRole,
  'changedAt' : IDL.Int,
  'changedBy' : IDL.Principal,
  'entityId' : IDL.Nat,
  'afterValue' : IDL.Text,
  'beforeValue' : IDL.Opt(IDL.Text),
  'entityType' : IDL.Text,
  'fieldName' : IDL.Text,
  'ipAddress' : IDL.Opt(IDL.Text),
  'reason' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CurrentUser = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const SyncRecord = IDL.Record({
  'id' : IDL.Nat,
  'lastEntityType' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'pendingChanges' : IDL.Nat,
  'deviceId' : IDL.Text,
  'lastSyncAt' : IDL.Int,
  'lastEntityId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
      [],
    ),
  'acknowledgeObservationCorrection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Observation, 'err' : IDL.Text })],
      [],
    ),
  'assignBed' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBedRecord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
      [],
    ),
  'createClinicalAlert' : IDL.Func(
      [IDL.Nat, AlertType, AlertSeverity, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
      [],
    ),
  'createClinicalNote' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        NoteType,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : ClinicalNote, 'err' : IDL.Text })],
      [],
    ),
  'createDiagnosisTemplate' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : DiagnosisTemplate, 'err' : IDL.Text })],
      [],
    ),
  'createEncounter' : IDL.Func(
      [IDL.Nat, EncounterType, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Encounter, 'err' : IDL.Text })],
      [],
    ),
  'createObservation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        ObservationType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Int,
      ],
      [IDL.Variant({ 'ok' : Observation, 'err' : IDL.Text })],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        OrderType,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : ClinicalOrder, 'err' : IDL.Text })],
      [],
    ),
  'createPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        Gender,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        PatientType,
      ],
      [Patient],
      [],
    ),
  'createPrescription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Time,
        IDL.Opt(IDL.Text),
        IDL.Vec(Medication),
        IDL.Opt(IDL.Text),
      ],
      [Prescription],
      [],
    ),
  'createVisit' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Opt(IDL.Text),
        VitalSigns,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        VisitType,
      ],
      [Visit],
      [],
    ),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'deletePrescription' : IDL.Func([IDL.Nat], [], []),
  'deleteVisit' : IDL.Func([IDL.Nat], [], []),
  'dischargeBed' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
      [],
    ),
  'getActiveOrdersByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClinicalOrder)],
      ['query'],
    ),
  'getAlertsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClinicalAlert)],
      ['query'],
    ),
  'getAllAuditEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAllBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
  'getAllDiagnosisTemplates' : IDL.Func(
      [],
      [IDL.Vec(DiagnosisTemplate)],
      ['query'],
    ),
  'getAllEncounters' : IDL.Func([], [IDL.Vec(Encounter)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getAuditTrail' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAvailableBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicalNotesByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClinicalNote)],
      ['query'],
    ),
  'getClinicalNotesByType' : IDL.Func(
      [IDL.Nat, NoteType],
      [IDL.Vec(ClinicalNote)],
      ['query'],
    ),
  'getCurrentUser' : IDL.Func([], [CurrentUser], []),
  'getDiagnosisTemplate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DiagnosisTemplate)],
      ['query'],
    ),
  'getEncountersByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Encounter)],
      ['query'],
    ),
  'getLastSyncTime' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Int)], ['query']),
  'getObservationsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Observation)],
      ['query'],
    ),
  'getObservationsByType' : IDL.Func(
      [IDL.Nat, ObservationType],
      [IDL.Vec(Observation)],
      ['query'],
    ),
  'getOccupiedBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
  'getOrdersByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClinicalOrder)],
      ['query'],
    ),
  'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
  'getPrescription' : IDL.Func([IDL.Nat], [IDL.Opt(Prescription)], ['query']),
  'getPrescriptionsByPatientId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPrescriptionsByVisitId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getUnacknowledgedAlerts' : IDL.Func([], [IDL.Vec(ClinicalAlert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
  'getVisitsByPatientId' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'migrateFromLocalStorage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordDeviceSync' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : SyncRecord, 'err' : IDL.Text })],
      [],
    ),
  'resolveAlert' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferBed' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
      [],
    ),
  'updateClinicalNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : ClinicalNote, 'err' : IDL.Text })],
      [],
    ),
  'updateDiagnosisTemplate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : DiagnosisTemplate, 'err' : IDL.Text })],
      [],
    ),
  'updateEncounter' : IDL.Func(
      [IDL.Nat, IDL.Nat, EncounterStatus, IDL.Opt(IDL.Int), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Encounter, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, OrderStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Variant({ 'ok' : ClinicalOrder, 'err' : IDL.Text })],
      [],
    ),
  'updatePatient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        Gender,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        PatientType,
      ],
      [Patient],
      [],
    ),
  'updatePrescription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Time,
        IDL.Opt(IDL.Text),
        IDL.Vec(Medication),
        IDL.Opt(IDL.Text),
      ],
      [Prescription],
      [],
    ),
  'updateVisit' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Opt(IDL.Text),
        VitalSigns,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        VisitType,
      ],
      [Visit],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertType = IDL.Variant({
    'AKI' : IDL.Null,
    'Hypotension' : IDL.Null,
    'CriticalLab' : IDL.Null,
    'Sepsis' : IDL.Null,
    'DrugInteraction' : IDL.Null,
    'Hypoxia' : IDL.Null,
    'AllergyContraindication' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'Info' : IDL.Null,
    'Critical' : IDL.Null,
    'Warning' : IDL.Null,
  });
  const ClinicalAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : AlertType,
    'acknowledgedAt' : IDL.Opt(IDL.Int),
    'acknowledgedBy' : IDL.Opt(IDL.Principal),
    'patientId' : IDL.Nat,
    'isAcknowledged' : IDL.Bool,
    'isResolved' : IDL.Bool,
    'triggeredAt' : IDL.Int,
    'triggeredBy' : IDL.Text,
    'message' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
    'severity' : AlertSeverity,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const ObservationStatus = IDL.Variant({
    'Corrected' : IDL.Null,
    'Final' : IDL.Null,
    'Preliminary' : IDL.Null,
  });
  const ObservationType = IDL.Variant({
    'Lab' : IDL.Null,
    'ExamFinding' : IDL.Null,
    'DrainMonitoring' : IDL.Null,
    'IntakeOutput' : IDL.Null,
    'Vital' : IDL.Null,
  });
  const StaffRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'medical_officer' : IDL.Null,
    'intern_doctor' : IDL.Null,
    'consultant_doctor' : IDL.Null,
    'staff' : IDL.Null,
    'nurse' : IDL.Null,
  });
  const VersionedRecord = IDL.Record({
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'version' : IDL.Nat,
    'createdByName' : IDL.Text,
    'createdByRole' : StaffRole,
    'changeReason' : IDL.Opt(IDL.Text),
  });
  const Observation = IDL.Record({
    'id' : IDL.Nat,
    'status' : ObservationStatus,
    'isDeleted' : IDL.Bool,
    'numericValue' : IDL.Opt(IDL.Float64),
    'value' : IDL.Text,
    'observationDate' : IDL.Int,
    'patientId' : IDL.Nat,
    'observationType' : ObservationType,
    'code' : IDL.Text,
    'unit' : IDL.Text,
    'recordedBy' : IDL.Principal,
    'normalRange' : IDL.Opt(IDL.Text),
    'recordedByName' : IDL.Text,
    'recordedByRole' : StaffRole,
    'interpretation' : IDL.Opt(IDL.Text),
    'versionInfo' : VersionedRecord,
    'encounterId' : IDL.Opt(IDL.Nat),
  });
  const BedStatus = IDL.Variant({
    'Empty' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Occupied' : IDL.Null,
  });
  const BedTransferEntry = IDL.Record({
    'toBed' : IDL.Text,
    'date' : IDL.Int,
    'fromBed' : IDL.Text,
    'reason' : IDL.Text,
  });
  const BedRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : BedStatus,
    'patientId' : IDL.Opt(IDL.Nat),
    'admissionDate' : IDL.Opt(IDL.Int),
    'transferHistory' : IDL.Vec(BedTransferEntry),
    'ward' : IDL.Text,
    'bedNumber' : IDL.Text,
    'patientName' : IDL.Opt(IDL.Text),
    'dischargeDate' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoteType = IDL.Variant({
    'SOAP' : IDL.Null,
    'Nursing' : IDL.Null,
    'DailyProgress' : IDL.Null,
    'General' : IDL.Null,
    'Handover' : IDL.Null,
    'Discharge' : IDL.Null,
  });
  const ClinicalNote = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'patientId' : IDL.Nat,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'authorRole' : StaffRole,
    'noteType' : NoteType,
    'isDraft' : IDL.Bool,
    'previousVersionIds' : IDL.Vec(IDL.Nat),
    'versionInfo' : VersionedRecord,
    'encounterId' : IDL.Opt(IDL.Nat),
    'noteSubtype' : IDL.Opt(IDL.Text),
  });
  const DiagnosisTemplate = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'icdCode' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'defaultDrugs' : IDL.Vec(IDL.Text),
    'defaultAdvice' : IDL.Vec(IDL.Text),
    'defaultInvestigations' : IDL.Vec(IDL.Text),
    'diagnosisNameBn' : IDL.Opt(IDL.Text),
    'diagnosisName' : IDL.Text,
    'defaultAdviceBn' : IDL.Vec(IDL.Text),
  });
  const EncounterType = IDL.Variant({
    'IPD' : IDL.Null,
    'OPD' : IDL.Null,
    'FollowUp' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const EncounterStatus = IDL.Variant({
    'Planned' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Encounter = IDL.Record({
    'id' : IDL.Nat,
    'status' : EncounterStatus,
    'encounterType' : EncounterType,
    'endDate' : IDL.Opt(IDL.Int),
    'patientId' : IDL.Nat,
    'previousVersions' : IDL.Vec(VersionedRecord),
    'providerName' : IDL.Text,
    'providerId' : IDL.Principal,
    'versionInfo' : VersionedRecord,
    'encounterId' : IDL.Text,
    'locationNotes' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Int,
  });
  const OrderType = IDL.Variant({
    'Medication' : IDL.Null,
    'Procedure' : IDL.Null,
    'Investigation' : IDL.Null,
    'LabTest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'Requested' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ClinicalOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'result' : IDL.Opt(IDL.Text),
    'patientId' : IDL.Nat,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'orderType' : OrderType,
    'orderedAt' : IDL.Int,
    'orderedBy' : IDL.Principal,
    'notes' : IDL.Opt(IDL.Text),
    'orderedByName' : IDL.Text,
    'orderedByRole' : StaffRole,
    'versionInfo' : VersionedRecord,
    'encounterId' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientType = IDL.Variant({
    'admitted' : IDL.Null,
    'outdoor' : IDL.Null,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'nameBn' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Opt(Time),
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'pastSurgicalHistory' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'patientType' : PatientType,
    'chronicConditions' : IDL.Vec(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const Medication = IDL.Record({
    'duration' : IDL.Text,
    'dose' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'diagnosis' : IDL.Opt(IDL.Text),
    'prescriptionDate' : Time,
    'medications' : IDL.Vec(Medication),
    'notes' : IDL.Opt(IDL.Text),
    'visitId' : IDL.Opt(IDL.Nat),
  });
  const VitalSigns = IDL.Record({
    'respiratoryRate' : IDL.Opt(IDL.Text),
    'temperature' : IDL.Opt(IDL.Text),
    'bloodPressure' : IDL.Opt(IDL.Text),
    'oxygenSaturation' : IDL.Opt(IDL.Text),
    'pulse' : IDL.Opt(IDL.Text),
  });
  const VisitType = IDL.Variant({
    'admitted' : IDL.Null,
    'outdoor' : IDL.Null,
  });
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'vitalSigns' : VitalSigns,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'visitDate' : Time,
    'visitType' : VisitType,
    'diagnosis' : IDL.Opt(IDL.Text),
    'historyOfPresentIllness' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'physicalExamination' : IDL.Opt(IDL.Text),
    'chiefComplaint' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'changedByName' : IDL.Text,
    'changedByRole' : StaffRole,
    'changedAt' : IDL.Int,
    'changedBy' : IDL.Principal,
    'entityId' : IDL.Nat,
    'afterValue' : IDL.Text,
    'beforeValue' : IDL.Opt(IDL.Text),
    'entityType' : IDL.Text,
    'fieldName' : IDL.Text,
    'ipAddress' : IDL.Opt(IDL.Text),
    'reason' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CurrentUser = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const SyncRecord = IDL.Record({
    'id' : IDL.Nat,
    'lastEntityType' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'pendingChanges' : IDL.Nat,
    'deviceId' : IDL.Text,
    'lastSyncAt' : IDL.Int,
    'lastEntityId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
        [],
      ),
    'acknowledgeObservationCorrection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Observation, 'err' : IDL.Text })],
        [],
      ),
    'assignBed' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBedRecord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
        [],
      ),
    'createClinicalAlert' : IDL.Func(
        [IDL.Nat, AlertType, AlertSeverity, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
        [],
      ),
    'createClinicalNote' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          NoteType,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : ClinicalNote, 'err' : IDL.Text })],
        [],
      ),
    'createDiagnosisTemplate' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : DiagnosisTemplate, 'err' : IDL.Text })],
        [],
      ),
    'createEncounter' : IDL.Func(
        [IDL.Nat, EncounterType, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Encounter, 'err' : IDL.Text })],
        [],
      ),
    'createObservation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          ObservationType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Int,
        ],
        [IDL.Variant({ 'ok' : Observation, 'err' : IDL.Text })],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          OrderType,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : ClinicalOrder, 'err' : IDL.Text })],
        [],
      ),
    'createPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          Gender,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          PatientType,
        ],
        [Patient],
        [],
      ),
    'createPrescription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Time,
          IDL.Opt(IDL.Text),
          IDL.Vec(Medication),
          IDL.Opt(IDL.Text),
        ],
        [Prescription],
        [],
      ),
    'createVisit' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Text),
          VitalSigns,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          VisitType,
        ],
        [Visit],
        [],
      ),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'deletePrescription' : IDL.Func([IDL.Nat], [], []),
    'deleteVisit' : IDL.Func([IDL.Nat], [], []),
    'dischargeBed' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
        [],
      ),
    'getActiveOrdersByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClinicalOrder)],
        ['query'],
      ),
    'getAlertsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClinicalAlert)],
        ['query'],
      ),
    'getAllAuditEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAllBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
    'getAllDiagnosisTemplates' : IDL.Func(
        [],
        [IDL.Vec(DiagnosisTemplate)],
        ['query'],
      ),
    'getAllEncounters' : IDL.Func([], [IDL.Vec(Encounter)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getAuditTrail' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAvailableBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicalNotesByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClinicalNote)],
        ['query'],
      ),
    'getClinicalNotesByType' : IDL.Func(
        [IDL.Nat, NoteType],
        [IDL.Vec(ClinicalNote)],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [CurrentUser], []),
    'getDiagnosisTemplate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DiagnosisTemplate)],
        ['query'],
      ),
    'getEncountersByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Encounter)],
        ['query'],
      ),
    'getLastSyncTime' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Int)], ['query']),
    'getObservationsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Observation)],
        ['query'],
      ),
    'getObservationsByType' : IDL.Func(
        [IDL.Nat, ObservationType],
        [IDL.Vec(Observation)],
        ['query'],
      ),
    'getOccupiedBeds' : IDL.Func([], [IDL.Vec(BedRecord)], ['query']),
    'getOrdersByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClinicalOrder)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
    'getPrescription' : IDL.Func([IDL.Nat], [IDL.Opt(Prescription)], ['query']),
    'getPrescriptionsByPatientId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPrescriptionsByVisitId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getUnacknowledgedAlerts' : IDL.Func(
        [],
        [IDL.Vec(ClinicalAlert)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
    'getVisitsByPatientId' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'migrateFromLocalStorage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordDeviceSync' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : SyncRecord, 'err' : IDL.Text })],
        [],
      ),
    'resolveAlert' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : ClinicalAlert, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferBed' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : BedRecord, 'err' : IDL.Text })],
        [],
      ),
    'updateClinicalNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : ClinicalNote, 'err' : IDL.Text })],
        [],
      ),
    'updateDiagnosisTemplate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : DiagnosisTemplate, 'err' : IDL.Text })],
        [],
      ),
    'updateEncounter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          EncounterStatus,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Encounter, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Variant({ 'ok' : ClinicalOrder, 'err' : IDL.Text })],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          Gender,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          PatientType,
        ],
        [Patient],
        [],
      ),
    'updatePrescription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Time,
          IDL.Opt(IDL.Text),
          IDL.Vec(Medication),
          IDL.Opt(IDL.Text),
        ],
        [Prescription],
        [],
      ),
    'updateVisit' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Text),
          VitalSigns,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          VisitType,
        ],
        [Visit],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };